In [32]:
from pymongo import MongoClient
import pymongo
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DB = 'PRO734'
MONGO_COLLECTION = 'Twitter_name_result'
MONGO_COLLECTION1 = 'News_result'

def mongo_connection(host, port, db, collection):
    try:
        conn = MongoClient(host, port)
        return conn[db][collection]
    except:
        raise

def mongo_logging(connection, content):
    try:
        connection.insert_one(content)
    except:
        raise

conn = mongo_connection(MONGO_HOST,MONGO_PORT,MONGO_DB,MONGO_COLLECTION )
conn1 = mongo_connection(MONGO_HOST,MONGO_PORT,MONGO_DB,MONGO_COLLECTION1 )

In [33]:
import pandas as pd

df = pd.DataFrame(list(conn.find()))
df1 = pd.DataFrame(list(conn1.find()))
final = pd.DataFrame()
#final['keyword'] = ''
#final['user_link'] = ''

In [34]:
df

,NE_ID,_id,twitter_name
0,476334,58da4b603004e32af8139585,[]
1,32627,58da4b623004e32af8139587,[]
2,39124,58da4b633004e32af8139589,[]
3,60827,58da4b653004e32af813958b,[]
4,34824,58da4b693004e33cbc04b58b,[]
5,36449,58da4b6b3004e33cbc04b58d,[]
6,37752,58da4b6c3004e33cbc04b58f,"[@swissifg, @bsafunds, @flanaganlyfe, @fion_li..."
7,38796,58da4b6e3004e33cbc04b591,[]
8,27120,58da4b703004e33cbc04b593,[]
9,39583,58da4b723004e33cbc04b595,[]
10,39736,58da4b743004e33cbc04b597,[]
11,40391,58da4b763004e33cbc04b599,[]
12,30201,58da4b783004e33cbc04b59b,[]
13,40004,58da4b7a3004e33cbc04b59d,[]
14,1791394,58da4b7c3004e32af813958d,"[@unemploymentmov, @playcritically, @rfscommis..."
15,40536,58da4b7c3004e33cbc04b59f,[]
16,27800,58da4b7e3004e33cbc04b5a1,[]
17,28446,58da4b803004e33cbc04b5a3,[]
18,37239,58da4b823004e33cbc04b5a5,[]
19,1794145,58da4b843004e33cbc04b5a7,[]
20,33353,58da4b863004e33cbc04b5a9,[]
21,18471,58da4b883004e33cbc04b5ab,[]
22,18863,58da4b8b3004e33cbc04b5ad,[@bioportfolio]
23,28062,58da4b8f3004e33cbc04b5af,"[@johnjayresearch, @tweetsanup, @mannegerell, ..."
24,6245,58da4b923004e33cbc04b5b1,[]
25,29832,58da4b983004e32af813958f,"[@davidbewart, @ashurst_au, @heartofhudds, @sy..."
26,1814587,58da4b9d3004e32af8139591,[]
27,1820092,58da4ba43004e33c3c241f6a,"[@karolinecqkan, @doemela, @maguire_fran, @ant..."
28,12755,58da4ba53004e33cbc04b5b3,"[@marylene58, @biancasavonrola, @enfusecon, @i..."
29,1794726,58da4ba93004e33cbc04b5b5,[]
...,...,...,...
65767,1820062,58dc0df83004e315785be871,[]
65768,1820063,58dc0dfa3004e315785be873,[]
65769,1820064,58dc0dfb3004e315785be875,[]
65770,1820065,58dc0dfc3004e315785be877,[]
65771,1820066,58dc0dfd3004e315785be879,[]
65772,1820067,58dc0dfe3004e315785be87b,[]
65773,1820068,58dc0dff3004e315785be87d,[]
65774,1820069,58dc0e003004e315785be87f,[]
65775,1820070,58dc0e013004e315785be881,[]
65776,1820071,58dc0e023004e315785be883,[]
65777,1820072,58dc0e033004e315785be885,[]
65778,1820073,58dc0e043004e315785be887,[]
65779,1820074,58dc0e053004e315785be889,[]
65780,1820075,58dc0e063004e315785be88b,[]
65781,1820076,58dc0e073004e315785be88d,[]
65782,1820077,58dc0e083004e315785be88f,[]
65783,1820078,58dc0e093004e315785be891,[]
65784,1820079,58dc0e0a3004e315785be893,[]
65785,1820080,58dc0e0b3004e315785be895,[]
65786,1820081,58dc0e0d3004e315785be897,[]
65787,1820082,58dc0e0e3004e315785be899,[]
65788,1820083,58dc0e0f3004e315785be89b,[]
65789,1820084,58dc0e103004e315785be89d,[]
65790,1820085,58dc0e113004e315785be89f,[]
65791,1820086,58dc0e123004e315785be8a1,[]
65792,1820087,58dc0e133004e315785be8a3,[]
65793,1820088,58dc0e143004e315785be8a5,[]
65794,1820089,58dc0e153004e315785be8a7,[]
65795,1820090,58dc0e163004e315785be8a9,[]
65796,1820091,58dc0e173004e315785be8ab,[]

In [6]:
for i in df.index:
    for j in range(len(df['twitter_name'][i])):
        df2 = pd.DataFrame([[df['NE_ID'][i], df['twitter_name'][i][j]]], columns = ['NE_ID', 'twitter_name'])
        final = final.append(df2, ignore_index=True)

In [9]:
final.to_csv('twitter_account_rr.csv', encoding='utf-8', index=False)

In [11]:
final2 = pd.DataFrame()
for i in df1.index:
    for j in range(len(df1['article_url'][i])):
        df2 = pd.DataFrame([[df1['NE_ID'][i], df1['article_url'][i][j]]], columns = ['NE_ID', 'article_url'])
        final2 = final2.append(df2, ignore_index=True)

In [13]:
final2.to_csv('news_rr.csv', encoding='utf-8', index=False)

In [3]:
import pandas as pd
df1 = pd.DataFrame(list(conn1.find()))
final = pd.DataFrame()

In [7]:
df1['count'] = df1['article_url'].apply(lambda x: len(x))

In [9]:
df1.to_csv('check_login.csv')

In [28]:
df1

,NE_ID,_id,article_url,count
0,476334,58da4b603004e32af8139586,[],0
1,32627,58da4b623004e32af8139588,[],0
2,39124,58da4b633004e32af813958a,[],0
3,60827,58da4b653004e32af813958c,[],0
4,34824,58da4b693004e33cbc04b58c,[],0
5,36449,58da4b6b3004e33cbc04b58e,[],0
6,37752,58da4b6c3004e33cbc04b590,[bloomberg.com -],1
7,38796,58da4b6e3004e33cbc04b592,[],0
8,27120,58da4b703004e33cbc04b594,[],0
9,39583,58da4b723004e33cbc04b596,[],0
10,39736,58da4b743004e33cbc04b598,[],0
11,40391,58da4b763004e33cbc04b59a,[],0
12,30201,58da4b783004e33cbc04b59c,[],0
13,40004,58da4b7a3004e33cbc04b59e,[],0
14,40536,58da4b7c3004e33cbc04b5a0,[],0
15,1791394,58da4b7e3004e32af813958e,"[2017remembrancebikeride.gofundraise.com.au -,...",31
16,27800,58da4b7e3004e33cbc04b5a2,[],0
17,28446,58da4b803004e33cbc04b5a4,[],0
18,37239,58da4b823004e33cbc04b5a6,[],0
19,1794145,58da4b843004e33cbc04b5a8,[],0
20,33353,58da4b863004e33cbc04b5aa,[],0
21,18471,58da4b883004e33cbc04b5ac,[],0
22,18863,58da4b8b3004e33cbc04b5ae,[bioportfolio.co.uk -],1
23,28062,58da4b903004e33cbc04b5b0,"[link.springer.com -, exchange4media.com -, en...",9
24,6245,58da4b923004e33cbc04b5b2,[],0
25,29832,58da4b9b3004e32af8139590,"[dailymail.co.uk -, crownresorts.com.au -, au....",40
26,1814587,58da4b9d3004e32af8139592,[],0
27,12755,58da4ba73004e33cbc04b5b4,"[ooyuz.com -, einpresswire.com -, upi.com -, t...",29
28,1794726,58da4ba93004e33cbc04b5b6,[],0
29,1820092,58da4baa3004e33c3c241f6b,"[sinonk.com -, mashable.com -, freekorea.us -,...",86
...,...,...,...,...
65766,1820062,58dc0df83004e315785be872,[],0
65767,1820063,58dc0dfa3004e315785be874,[],0
65768,1820064,58dc0dfb3004e315785be876,[],0
65769,1820065,58dc0dfc3004e315785be878,[],0
65770,1820066,58dc0dfd3004e315785be87a,[],0
65771,1820067,58dc0dfe3004e315785be87c,[],0
65772,1820068,58dc0dff3004e315785be87e,[],0
65773,1820069,58dc0e003004e315785be880,[],0
65774,1820070,58dc0e013004e315785be882,[],0
65775,1820071,58dc0e023004e315785be884,[],0
65776,1820072,58dc0e033004e315785be886,[],0
65777,1820073,58dc0e043004e315785be888,[],0
65778,1820074,58dc0e053004e315785be88a,[],0
65779,1820075,58dc0e063004e315785be88c,[],0
65780,1820076,58dc0e073004e315785be88e,[],0
65781,1820077,58dc0e083004e315785be890,[],0
65782,1820078,58dc0e093004e315785be892,[],0
65783,1820079,58dc0e0a3004e315785be894,[],0
65784,1820080,58dc0e0b3004e315785be896,[],0
65785,1820081,58dc0e0d3004e315785be898,[],0
65786,1820082,58dc0e0e3004e315785be89a,[],0
65787,1820083,58dc0e0f3004e315785be89c,[],0
65788,1820084,58dc0e103004e315785be89e,[],0
65789,1820085,58dc0e113004e315785be8a0,[],0
65790,1820086,58dc0e123004e315785be8a2,[],0
65791,1820087,58dc0e133004e315785be8a4,[],0
65792,1820088,58dc0e143004e315785be8a6,[],0
65793,1820089,58dc0e153004e315785be8a8,[],0
65794,1820090,58dc0e163004e315785be8aa,[],0
65795,1820091,58dc0e173004e315785be8ac,[],0

In [18]:
from psycopg2 import connect
import pandas as pd
import numpy as np
import requests
import psycopg2 as db

NE_DB = "dbname='rest_in_peace' user='dbo' host='10.0.0.137' password='sentifi'"
PROFILE_DB = "dbname='da0' user='dbw' host='da0.ssh.sentifi.com' password='sentifi.da0'"

# Connect to the Postgres Database
def connect_postgres():
    try:
        conn = db.connect(NE_DB)
        print("Initialised Connection")
        return conn
    except:
        print("I am unable to connect to the database")

In [23]:
conn = connect_postgres()
cur = conn.cursor()
cur.execute("set statement_timeout to 300000; select pg_sleep(2);")
result_df = pd.DataFrame()
NE_list = str(tuple(df1['NE_ID']))
query = """SELECT named_entity_id, name FROM named_entity WHERE named_entity_id in {0} """.format(NE_list)
cur.execute(query)
temp = cur.fetchall()
temp = map(list, temp)
#print(list(temp))
df = pd.DataFrame(list(temp))
result_df = pd.concat([result_df, df])
conn.close()

Initialised Connection

             0                          1
0            1              Public Sector
1            2                Bond Market
2            3                 BRICS Econ
3            4                 China Econ
4            5            Economic Growth
5            6           Emerging Markets
6            7              Interest Rate
7            9              Luxury Market
8           10          Market Volatility
9           15              Cyprus Crisis
10          16                       Debt
11          17                  Deflation
12          24                        GDP
13          27                       HNWI
14          31            Private Banking
15          32  Private Equity Holding AG
16          39               Unemployment
17          41                        AUD
18          42                        CAD
19          46                        EUR
20          50                        JPY
21          51                        MXN
22          54                        SEK
23          55                        SGD
24          56                        TRY
25          57                        USD
26          61                 Bill Gross
27          62             Boris Collardi
28          63               Brady Dougan
29          64            Widmer-Schlumpf
...        ...                        ...
60771  1834501       Jamaica Money Market
60772  1834502      Hardware & Lumber Ltd
60773  1834503   Sterling Investments Ltd
60774  1834504      PanJam Investment Ltd
60775  1834505    Jamaica Producers Group
60776  1834506               Carreras Ltd
60777  1834507         Empresa General de
60778  1834508     Grupo BanDelta Holding
60779  1834509       Latinex Holdings Inc
60780  1834510           Odin Energy Corp
60781  1834511                   GB Group
60782  1834512              Grupo Melo SA
60783  1834513       Indesa Holdings Corp
60784  1834514           Golden Forest SA
60785  1834515          Istmo Compania de
60786  1834516      Tropical Resorts Intl
60787  1834517              Grupo Assa SA
60788  1834518     BG Financial Group Inc
60789  1834519          Rey Holdings Corp
60790  1834520       Latinex Holdings Inc
60791  1834521                 Tower Corp
60792  1834522            MHC Holding Ltd
60793  1834523    Empresas Tagaropulos SA
60794  1834524        IFL Enterprises Ltd
60795  1834525            Next Games Corp
60796  1834526   Vishvesham Inv & Trading
60797  1834527         Ontic Finserve Ltd
60798  1834528    180 Degree Capital Corp
60799  1834529          Jash Dealmark Ltd
60800  1834530         Sarthak Metals Ltd

[60801 rows x 2 columns]

In [26]:
result_df.columns = ['NE_ID', 'NE_NAME']

In [27]:
result_df

         NE_ID                    NE_NAME
0            1              Public Sector
1            2                Bond Market
2            3                 BRICS Econ
3            4                 China Econ
4            5            Economic Growth
5            6           Emerging Markets
6            7              Interest Rate
7            9              Luxury Market
8           10          Market Volatility
9           15              Cyprus Crisis
10          16                       Debt
11          17                  Deflation
12          24                        GDP
13          27                       HNWI
14          31            Private Banking
15          32  Private Equity Holding AG
16          39               Unemployment
17          41                        AUD
18          42                        CAD
19          46                        EUR
20          50                        JPY
21          51                        MXN
22          54                        SEK
23          55                        SGD
24          56                        TRY
25          57                        USD
26          61                 Bill Gross
27          62             Boris Collardi
28          63               Brady Dougan
29          64            Widmer-Schlumpf
...        ...                        ...
60771  1834501       Jamaica Money Market
60772  1834502      Hardware & Lumber Ltd
60773  1834503   Sterling Investments Ltd
60774  1834504      PanJam Investment Ltd
60775  1834505    Jamaica Producers Group
60776  1834506               Carreras Ltd
60777  1834507         Empresa General de
60778  1834508     Grupo BanDelta Holding
60779  1834509       Latinex Holdings Inc
60780  1834510           Odin Energy Corp
60781  1834511                   GB Group
60782  1834512              Grupo Melo SA
60783  1834513       Indesa Holdings Corp
60784  1834514           Golden Forest SA
60785  1834515          Istmo Compania de
60786  1834516      Tropical Resorts Intl
60787  1834517              Grupo Assa SA
60788  1834518     BG Financial Group Inc
60789  1834519          Rey Holdings Corp
60790  1834520       Latinex Holdings Inc
60791  1834521                 Tower Corp
60792  1834522            MHC Holding Ltd
60793  1834523    Empresas Tagaropulos SA
60794  1834524        IFL Enterprises Ltd
60795  1834525            Next Games Corp
60796  1834526   Vishvesham Inv & Trading
60797  1834527         Ontic Finserve Ltd
60798  1834528    180 Degree Capital Corp
60799  1834529          Jash Dealmark Ltd
60800  1834530         Sarthak Metals Ltd

[60801 rows x 2 columns]

In [29]:
merge_df = pd.merge(left=df1, right=result_df, how='outer', on='NE_ID')

In [31]:
merge_df.to_csv('need_to_check.csv')