In [2]:
from psycopg2 import connect
import pandas as pd
import numpy as np
import requests
#import psycopg2
import psycopg2 as db

NE_DB = "dbname='rest_in_peace' user='dbo' host='10.0.0.137' password='sentifi'"
PROFILE_DB = "dbname='da0' user='dbw' host='da0.ssh.sentifi.com' password='sentifi.da0'"

def connect_postgres():
    try:
        conn = db.connect(NE_DB)
        print("Initialised Connection")
        return conn
    except:
        print "I am unable to connect to the database"

In [8]:
conn = connect_postgres()
cur = conn.cursor()
cur.execute("set statement_timeout to 30000000; select pg_sleep(2);")
query = """SELECT named_entity_id, status, name, shortname, legalname FROM "named_entity" WHERE status in ('1', '2', '4')"""
cur.execute(query)
temp = cur.fetchall()
temp = map(list, temp)
df = pd.DataFrame(temp)
df.columns = ['named_entity_id', 'status', 'name', 'shortname', 'legalname']
conn.close()

Initialised Connection

In [9]:
df

,named_entity_id,status,name,shortname,legalname
0,135320,3,Eline van Beek (elinevb),None,None
1,137020,3,Jesper Tornbjerg (JesperTornbjerg),None,None
2,476334,1,China Fin Market,None,None
3,32627,1,Shin-Nihon Tatemono,Shin-Nihon Tatemono Co.,Shin-Nihon Tatemono Co Ltd
4,765926,3,TradingFloor,None,None
5,511972,3,Cam Ellis,None,None
6,520313,3,Nissa,None,None
7,1091239,3,acnnewswire,None,None
8,39124,1,Welcron Kangwon Co Ltd,Welcron Kangwon,Welcron Kangwon Co Ltd
9,60827,1,KRW,Won,South Korean won
10,1791394,2,Mittagong,None,Mittagong
11,41870,3,Sarah Mishkin,,
12,29832,1,Ramsay Health Care,Ramsay Health Care,Ramsay Health Care Ltd
13,1814587,1,San-Ai Oil Co Ltd,San-Ai Oil,San-Ai Oil Co Ltd
14,725313,1,Entertainment Sector,None,None
15,1815125,1,SACO,Saudi Co for Hardware,Saudi Company for Hardware
16,1808730,1,Agrowill Group AB,None,Agrowill Group AB
17,511973,3,Lori Parker,None,None
18,511974,3,Micheal Scott,None,None
19,520314,3,Nissim Aciman,None,None
20,16962,1,Hankuk Package Co Ltd,Hankuk Package,Hankuk Package Co Ltd
21,21416,1,Korea Plasma Technology U,Korea Plasma Technology U,Korea Plasma Technology U Co Ltd
22,1815148,1,EIC,Electrical Industries,Electrical Industries Co
23,511977,3,Tina Ann Graves,None,None
24,39566,1,Woowon Development Co Ltd,Woowon Development,Woowon Development Co Ltd
25,1815155,1,SABIC,Saudi Basic Industries,Saudi Basic Industries Corp
26,1815158,1,SVCP,None,Saudi Vitrified Clay Pipes Co
27,511980,3,Skhawaja,None,None
28,511981,3,Replay Rayy,None,None
29,511982,3,11u60,None,None
...,...,...,...,...,...
1621712,1132906,3,Jama Jack,None,None
1621713,1586336,3,Chandan Chawhan,None,None
1621714,954145,3,Danielle Park,None,None
1621715,1469992,3,Thales Barreto,None,None
1621716,752113,3,,None,None
1621717,1539429,3,enricka julien,None,None
1621718,1695864,3,Mtl.,None,None
1621719,1451075,3,Splooge McButt,None,None
1621720,1399529,3,Anthony Marsland,None,None
1621721,1117843,3,Stop Self Harm,None,None
1621722,1074247,3,Brad Vooren,None,None
1621723,1691208,3,Jessi♛,None,None
1621724,822652,3,Fabio Villani,None,None
1621725,1271312,3,Chris Lingebach,None,None
1621726,1354230,3,,None,None
1621727,1341685,3,Dakx Turcotte,None,None
1621728,1140481,3,seغaج,None,None
1621729,1339344,3,pk yarnell,None,None
1621730,1172487,3,Janet Clark Williams,None,None
1621731,1488289,3,Rutuja,None,None
1621732,961766,3,,None,None
1621733,972681,3,,None,None
1621734,1207200,3,Sinéad Nolan,None,None
1621735,1433459,3,Lourdes Codina,None,None
1621736,1116865,3,Zainab Salbi,None,None
1621737,1269277,3,Lewis Chandler,None,None
1621738,1309049,3,Juan Sotomayor,None,None
1621739,752199,3,Martin Tapfumaneyi Chemhere,None,None
1621740,886994,3,Tim Smart,None,None
1621741,1050079,3,Julia Garrett,None,None